name: CI/CD Pipeline

on:
  push:
    branches: [master] # Run on pushes to master
  pull_request:
    branches: [master] # Run on PRs to master

jobs:
  # 1. Lint step
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  # 2. Test step
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint # ✅ runs only if lint passed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npm run test:ci
        # package.json -> "test:ci": "vitest run --coverage"

  # 3. Build step
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test # ✅ runs only if tests passed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
